import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import homepic from "/public/images/profile/cleanhomepipc.png";
import Image from "next/image";
import AnimatedTexts from "@/components/AnimatedTexts";
import Link from "next/link";
import HireMe from "@/components/HireMe";
 

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AH's Website Portfolio</title>
        <meta name="Portfolio" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <AnimatedTexts
                text="Turning visionary ideas into tech-powered reality."
                className="text-6xl text-left break-words whitespace-normal "
              />
              <p className="my-4 text-base font-medium">
                As an adept full-stack developer and seasoned veteran, I deeply
                grasp the significance of consistently delivering innovative
                solutions to intricate challenges. Explore my recent projects
                and articles highlighting my expertise in Full Stack
                Development.{" "}
              </p>
              <div className="flex items-center self-start mt-2 ">
                <Link
                  href="/AHResume.pdf"
                  target="_blank"
                  className={
                    "flex items-center bg-dark text-light px-6 py-2 rounded-lg mr-2 text-lg font-semibold hover:bg-light hover:text-dark " +
                    "border-2 border-solid border-transparent dark:bg-light hover:border-dark dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  }
                >
                  Resume
                </Link>
                <Link
                  href="mailto:aa.hernandez7602@gmail.com"
                  target={"_blank"} 
                  className={
                    "flex items-center bg-dark text-light px-6 py-2 rounded-lg mr-2 text-lg font-semibold hover:bg-light hover:text-dark " +
                    "border-2 border-solid border-transparent hover:border-dark  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  }
                >
                  Contact
                </Link>
              </div>
            </div>
            <div className="flex w-full">
              <Image src={homepic} alt="AH" className="w-full h-full ml-10 " priority />
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  );
}
